### ISSUE TITLE
flag_parser flag_char unknown character 

### ISSUE THREAD

**Issue by tyler-keller** [CSCI-442-Mines/project-5-starter#3]
Hey y'all,

I'm running into the same issue w/ parse_flags as with P4.

Changing (flag_parser.cpp [44]):
```
char flag_char;
```

To:
```
int flag_char;
```

fixed it though.

**Comment by Wakeful-Cloud** [comment]
Fixed in 0cc8eea647ac87d14b0b92bf51ca10735aa09cf2

**Comment by tyler-keller** [comment]
Cheers!
